---
# separated since needed in update
- name: generate mqtt json password using {{ aws_ecr_account }} {{ aws_ecr_region }} {{ wnt_version }}
  shell: "cd {{ service_home }} && ./generate_user_keys.sh"
  register: register_mqtt_json_password

- name: generate mqttlib json password using {{ aws_ecr_account }} {{ aws_ecr_region }} {{ wnt_version }}
  shell: "cd {{ service_home }} && ./generate_user_keys.sh"
  register: register_mqttlib_json_password

- name: set secrets
  set_fact:
    wnt_mqtt_json_password: "{{ (register_mqtt_json_password.stdout|from_json).password }}"
    wnt_mqttlib_json_password: "{{ (register_mqttlib_json_password.stdout|from_json).password }}"

