# Wirepas Oy 2018
#
# Generates keys and set secrets for wnt components
#
# wirepas Oy
---

- name: generate admin password using {{ aws_ecr_account }} {{ aws_ecr_region }} {{ wnt_version }}
  shell: "cd {{ service_home }} && ./generate_user_keys.sh"
  register: wnt_admin_password

- name: generate operator password using {{ aws_ecr_account }} {{ aws_ecr_region }} {{ wnt_version }}
  shell: "cd {{ service_home }} && ./generate_user_keys.sh"
  register: wnt_operator_password

- name: generate mqtt master password using {{ aws_ecr_account }} {{ aws_ecr_region }} {{ wnt_version }}
  shell: "cd {{ service_home }} && ./generate_user_keys.sh"
  register: register_mqtt_master_password

- name: generate mqtt gateway password using {{ aws_ecr_account }} {{ aws_ecr_region }} {{ wnt_version }}
  shell: "cd {{ service_home }} && ./generate_user_keys.sh"
  register: register_mqtt_gateway_password

- name: generate influx admin username
  shell: "cd {{ service_home }} && ./generate_user_keys.sh"
  register: register_influx_admin_username

- name: generate influx read username
  shell: "openssl rand -base64 32 | tr -dc '[:alnum:]\n\r'"
  register: register_influx_read_user

- name: generate influx read password
  shell: "openssl rand -base64 32 | tr -dc '[:alnum:]\n\r'"
  register: register_influx_read_password

- name: generate influx admin token
  shell: "openssl rand -base64 32 | tr -dc '[:alnum:]\n\r'"
  register: register_influx_admin_token

- name: generate influx admin password using {{ aws_ecr_account }} {{ aws_ecr_region }} {{ wnt_version }}
  shell: "cd {{ service_home }} && ./generate_user_keys.sh"
  register: register_influx_admin_password

- name: generate postgres password using {{ aws_ecr_account }} {{ aws_ecr_region }} {{ wnt_version }}
  shell: "cd {{ service_home }} && ./generate_user_keys.sh"
  register: register_postgres_password

- name: set secrets
  set_fact:
    wnt_admin_password_hash: "{{ (wnt_admin_password.stdout|from_json).password_hash }}"
    wnt_admin_password: "{{ (wnt_admin_password.stdout|from_json).password }}"
    wnt_operator_password_hash: "{{ (wnt_operator_password.stdout|from_json).password_hash }}"
    wnt_operator_password: "{{ (wnt_operator_password.stdout|from_json).password }}"
    wnt_mqtt_master_username: "{{ wnt_mqtt_master_username | default('mqttmasteruser') }}"
    wnt_mqtt_master_password: "{{ (register_mqtt_master_password.stdout|from_json).password }}"
    wnt_mqtt_gateway_username: "{{ wnt_mqtt_gateway_username }}"
    wnt_mqtt_gateway_password: "{{ (register_mqtt_gateway_password.stdout|from_json).password }}"
    wnt_influx_admin_username: "{{ (register_influx_admin_username.stdout|from_json).password }}"
    wnt_influx_admin_password: "{{ (register_influx_admin_password.stdout|from_json).password }}"
    wnt_influx_admin_token: "{{ register_influx_admin_token.stdout }}"
    wnt_influx_read_user: "{{ register_influx_read_user.stdout }}"
    wnt_influx_read_password: "{{ register_influx_read_password.stdout }}"
    wnt_postgres_password: "{{ (register_postgres_password.stdout|from_json).password }}"

- name: Create MQTT_JSON credentials
  import_tasks: generate_mqttjson_credentials.yml

- name: Add credentials to AWS
  import_tasks: generate_credentials_to_aws.yml
  when: aws_profile is defined and aws_profile != ""



