---
- name: Create admin credentials in parameter store
  command: aws --profile "{{ aws_profile }}" ssm put-parameter --name "/wirepas/{{ instance_name }}/wnt/credentials/admin" --value "{{ wnt_admin_password }}" --type "SecureString" --region {{ aws_region }} --overwrite
  delegate_to: localhost
  when: wnt_admin_password is defined and wnt_admin_password != ""

- name: Create mqttmasteruser credentials in parameter store
  command: aws --profile "{{ aws_profile }}" ssm put-parameter --name "/wirepas/{{ instance_name }}/wnt/credentials/mqttmasteruser" --value "{{ wnt_mqtt_master_password }}" --type "SecureString" --region {{ aws_region }} --overwrite
  delegate_to: localhost
  when: wnt_mqtt_master_password is defined and wnt_mqtt_master_password != ""

- name: Create mqtt_gateway credentials in parameter store
  command: aws --profile "{{ aws_profile }}" ssm put-parameter --name "/wirepas/{{ instance_name }}/wnt/credentials/mqttgateway" --value "{{ wnt_mqtt_gateway_password }}" --type "SecureString" --region {{ aws_region }} --overwrite
  delegate_to: localhost
  when: wnt_mqtt_gateway_password is defined and wnt_mqtt_gateway_password != ""

- name: Store MQTT_JSON credentials
  import_tasks: store_mqtt_credentials.yml
