---
- name: Store mqtt_json credentials in parameter store
  command: aws --profile "{{ aws_profile }}" ssm put-parameter --name "/wirepas/{{ instance_name }}/wnt/credentials/mqttjson" --value "{{ wnt_mqtt_json_password  }}" --type "SecureString" --region {{ aws_region }} --overwrite
  delegate_to: localhost
  when: aws_profile is defined and aws_profile != "" and wnt_mqtt_json_password is defined and wnt_mqtt_json_password != ""

- name: Store mqttlib_json credentials in parameter store
  command: aws --profile "{{ aws_profile }}" ssm put-parameter --name "/wirepas/{{ instance_name }}/wnt/credentials/mqttlibjson" --value "{{ wnt_mqttlib_json_password  }}" --type "SecureString" --region {{ aws_region }} --overwrite
  delegate_to: localhost
  when: aws_profile is defined and aws_profile != "" and wnt_mqttlib_json_password is defined and wnt_mqttlib_json_password != ""
