---
- name: Write WPE component state
  ansible.builtin.command: docker inspect --format {{ "'{{" }}.State.Status{{ "}}'" }} {{ item }}
  register: status_results
  changed_when: false
  loop: "{{ wpe_services_list }}"
- name: Populate statuses dict
  set_fact:
    wpe_statuses_dict: "{{ wpe_statuses_dict|default({}) | combine( {item.item: item.stdout} ) }}"
  with_items: "{{ status_results.results }}"
- set_fact:
    wpe_running: false
- set_fact:
    wpe_running: true
  when: >
    wpe_statuses_dict['wpe-flow'] is defined and wpe_statuses_dict['wpe-flow'] == "running" and
    wpe_statuses_dict['wpe-subscriber'] is defined and wpe_statuses_dict['wpe-subscriber'] == "running" and
    wpe_statuses_dict['wpe-core'] is defined and wpe_statuses_dict['wpe-core'] == "running"
