- block:
    - name: verify that the self-hosting keys are valid to login to the docker registry
      shell: $(aws ecr get-login --region {{ aws_ecr_region }} --no-include-email --registry-id {{ aws_ecr_account }})

    - name: verify that a docker image can be retrieved from the repository
      command: "docker pull {{ aws_ecr_repository }}/wnt_vernemq:{{ wnt_version }}"

  rescue:
    - name: handle credential validation failures
      fail:
        msg: >
          The Self-hosting keys provided are not valid. Please ensure that you are using self hosting keys provided by Wirepas 
          for your account (i.e. credentials found in WNT4_HostingKeys_<company_namne>.txt typically shared by Wirepas support via your Sharefile account).
          In case of an upgrade from WNT3 to WNT4, please verify that you have provided WNT4 self-hosting keys (i.e. you are not using the older WNT3 credentials).
