# Wirepas Oy 2019
---
- name: create aws folder
  file:
   path: "{{instance_admin_home}}/.aws/"
   state: directory
   mode: 0755

- name: set aws config
  template:
    src: "aws_configure.j2"
    dest: "{{instance_admin_home}}/.aws/config"

- name: set aws credentials
  template:
    src: "aws_credentials.j2"
    dest: "{{instance_admin_home}}/.aws/credentials"
  tags: update_host_actions
