---
- name: verify that aws credentials have been provided
  assert:
    that:
      - aws_access_key_id is defined and aws_access_key_id != None and aws_secret_access_key is defined and aws_secret_access_key != None
    fail_msg: Could not find AWS credentials. Please provide AWS credentials (aws_access_key_id and aws_secret_access_key) in vars/vars/aws_account.yml
    quiet: true
  
- name: setup aws credentials
  import_tasks: host_aws_credentials.yml

- name: check the validity of the provided credentials
  import_tasks: check_credentials_validity.yml
